[package]
name = "rustnet_scan"
version = "1.0.0"
edition = "2021"
authors = ["Security Team"]
description = "A high-performance network vulnerability scanner written in Rust"

[dependencies]
# Core dependencies
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.5"
chrono = "0.4"
rayon = "1.5"
pnet = "0.31"
ipnetwork = "0.18"
trust-dns-resolver = "0.21"
lazy_static = "1.4"
libc = "0.2"
colored = "2.0"
rand = "0.8"

# For CVE API integration
reqwest = { version = "0.11", features = ["blocking", "json"] }

# OS-specific dependencies
[target.'cfg(windows)'.dependencies]
winreg = "0.10"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
